# Generated by Django 4.0.3 on 2022-04-10 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powtoon', '0003_alter_powtoon_contentjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powtoon',
            name='sharedWith',
            field=models.ManyToManyField(blank=True, related_name='shared_with_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
