# Generated by Django 4.0.3 on 2022-04-10 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powtoon', '0004_alter_powtoon_sharedwith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powtoon',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
